db.url=
db.user=
db.password=

songs.folder=
artwork.folder=

app.port=8808
cors.allowed.origins=http://localhost:3000
session.cookie.secure=false

admin.username=admin
admin.password=ourmusic

ffmpeg.path=
subsonic.auth.secret=
